{
  imports = [
    ../modules/audio.nix
    ../modules/bluetooth.nix
    ../modules/cosmic-desktop.nix
    ../modules/displaymanager.nix
    ../modules/distrobox.nix
    ../modules/documentation.nix
    ../modules/environment-variables.nix
    ../modules/firewall.nix
    ../modules/flatpak.nix
    ../modules/fonts.nix
    ../modules/fwupd.nix
    ../modules/gc.nix
    ../modules/gnome.nix
    ../modules/graphics.nix
    ../modules/hacking.nix
    ../modules/hyprland.nix
    ../modules/i18n.nix
    ../modules/info-fetchers.nix
    ../modules/kernel.nix
    ../modules/macchanger.nix
    ../modules/networking.nix
    ../modules/nh.nix
    ../modules/nix-settings.nix
    ../modules/nix-ld.nix
    ../modules/nix-tools.nix
    ../modules/nvf.nix
    ../modules/ollama.nix
    ../modules/openssh.nix
    ../modules/plasma.nix
    ../modules/powermanagement.nix
    ../modules/rust.nix
    ../modules/scanner.nix
    ../modules/security.nix
    ../modules/stylix.nix
    ../modules/syncthing.nix
    ../modules/systemtools.nix
    ../modules/time.nix

    ../modules/ventoy.nix
    ../modules/virtualisation.nix
    ../modules/wine.nix
    #../modules/xdg.nix
    ../modules/xfce.nix
    ../modules/yubikey.nix
    ../modules/zram.nix
    ../modules/zsh.nix
    ../modules/database
  ];
}
