{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./documentation.nix
    ./displaymanager.nix
    ./flatpak.nix
    ./security.nix
    ./environment-variables.nix
    ./fonts.nix
    ./fwupd.nix
    ./gc.nix
    ./i18n.nix
    ./plasma.nix
    ./hyprland.nix
    ./graphics.nix
    ./hacking.nix
    ./info-fetchers.nix
    ./kernel.nix
    #./networking.nix
    #./firewall.nix
    ./nh.nix
    ./nix-settings.nix
    ./nix-tools.nix
    ./powermanagement.nix
    ./ollama.nix
    ./rust.nix
    ./virtualisation.nix
    ./xdg.nix
    ./zsh.nix
  ];
}
