{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./catppuccin.nix
    ./cockroach.nix
    ./cosmic-desktop.nix
    ./database-tools.nix
    ./displaymanager.nix
    ./distrobox.nix
    ./documentation.nix
    ./environment-variables.nix
    ./firewall.nix
    ./flatpak.nix
    ./fonts.nix
    ./fwupd.nix
    ./gc.nix
    ./graphics.nix
    ./hacking.nix
    ./hyprland.nix
    ./i18n.nix
    ./info-fetchers.nix
    ./kernel.nix
    ./macchanger.nix
    ./mariadb.nix
    ./mongodb.nix
    ./networking.nix
    ./nh.nix
    ./nix-settings.nix
    ./nix-tools.nix
    # ./nvf.nix
    ./ollama.nix
    ./openssh.nix
    ./plasma.nix
    ./postgres.nix
    ./powermanagement.nix
    ./redis.nix
    ./rust.nix
    ./scanner.nix
    ./security.nix
    ./syncthing.nix
    ./virtualisation.nix
    ./wine.nix
    ./xdg.nix
    ./yubikey.nix
    ./zram.nix
    ./zsh.nix
  ];
}
