{
  imports = [
    ../modules/nixpkgs.nix
    ../modules/cli
    ../modules/alacritty.nix
    ../modules/cursor.nix
    ../modules/fish.nix
    ../modules/flatpak.nix
    ../modules/ghostty.nix
    ../modules/graphic.nix
    ../modules/helix.nix
    ../modules/kitty.nix
    ../modules/latex.nix
    ../modules/libreoffice.nix
    ../modules/meld.nix
    ../modules/messenger.nix
    ../modules/mission-center.nix
    ../modules/multimedia.nix
    ../modules/nvf.nix
    ../modules/obs-studio.nix
    ../modules/pgbench.nix
    ../modules/qt-gtk-dconf.nix
    ../modules/sh.nix
    ../modules/starship.nix
    ../modules/stylix.nix
    ../modules/tmux.nix
    ../modules/torrent.nix
    ../modules/udiskie.nix
    ../modules/vscodium.nix
    ../modules/wallpapers.nix
    # ../modules/wezterm.nix #Broken for intel vulcan
    ../modules/windsurf.nix #Unfree package
    ../modules/xdg.nix
    ../modules/zellij.nix
    ../modules/zoxide.nix
    ../modules/hyprland
    ../modules/browsers
    ../modules/languages
  ];
}
