{
  imports = [
    ./alacritty.nix
    ./atiun.nix
    ./browsers.nix
    ./catppuccin.nix
    ./f3.nix
    ./fastfetch.nix
    ./fish.nix
    ./git.nix
    #./golang.nix
    #./graphic.nix
    ./gtk.nix
    #./helix.nix
    #./k9s.nix
    ./kitty.nix
    ./language-servers.nix
    #./latex.nix
    ./lf.nix
    ./mc.nix
    #./meld.nix
    #./messenger.nix
    ./mission-center.nix
    ./multimedia.nix
    ./node.nix
    #./obs-studio.nix
    ./pgbench.nix
    ./pyprland.nix
    ./qt.nix
    ./ranger.nix
    ./sh.nix
    ./starship.nix
    ./tmux.nix
    #./torrent.nix
    ./typescript.nix
    ./vscode.nix
    ./wallpapers.nix
    ./wezterm.nix
    ./xdg.nix
    ./yazi.nix
    #./zed-editor.nix
    ./zellij.nix
    ./zoxide.nix
    ./zsh.nix
    ./hyprland
  ];
}
