{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./cosmic-desktop.nix
    ./displaymanager.nix
    ./distrobox.nix
    ./documentation.nix
    ./environment-variables.nix
    ./firewall.nix
    ./flatpak.nix
    ./fonts.nix
    ./fwupd.nix
    ./gc.nix
    ./gnome.nix
    ./graphics.nix
    ./hacking.nix
    ./hyprland.nix
    ./i18n.nix
    ./info-fetchers.nix
    ./kernel.nix
    ./macchanger.nix
    ./networking.nix
    ./nh.nix
    ./nix-ld.nix
    ./nix-settings.nix
    ./nix-tools.nix
    ./nvf.nix
    ./ollama.nix
    ./openssh.nix
    ./plasma.nix
    ./powermanagement.nix
    ./rust.nix
    ./scanner.nix
    ./security.nix
    ./stylix.nix
    ./syncthing.nix
    ./systemtools.nix
    ./time.nix
    ./ventoy.nix
    ./virtualisation.nix
    ./wine.nix
    #./xdg.nix
    ./xfce.nix
    ./yubikey.nix
    ./zram.nix
    ./zsh.nix
    ./database
  ];
}
