{
  imports = [
    ../../common/modules/audio.nix
    ../../common/modules/bluetooth.nix
    ../../common/modules/bootloader.nix
    ../../common/modules/documentation.nix
    ../../common/modules/displaymanager.nix
    ../../common/modules/security.nix
    ../../common/modules/environment-variables.nix
    ../../common/modules/fonts.nix
    ../../common/modules/fwupd.nix
    ../../common/modules/gc.nix
    ../../common/modules/i18n.nix
    ../../common/modules/plasma.nix
    ../../common/modules/hyprland.nix
    ../../common/modules/graphics.nix
    ../../common/modules/hacking.nix
    ../../common/modules/info-fetchers.nix
    ../../common/modules/kernel.nix
    ../../common/modules/networking.nix
    ../../common/modules/dns.nix
    ../../common/modules/firewall.nix
    ../../common/modules/nh.nix
    ../../common/modules/nix-settings.nix
    ../../common/modules/nix-tools.nix
    ../../common/modules/lsp.nix
    ../../common/modules/powermanagement.nix
    ../../common/modules/ollama.nix
    #../../common/modules/rust.nix
    ../../common/modules/rust-fenix.nix
    ../../common/modules/virtualisation.nix
    ../../common/modules/xdg.nix
  ];
}
