{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./bootloader.nix
    ./displaymanager.nix
    ./documentation.nix
    ./cachix.nix
    ./security.nix
    ./environment-variables.nix
    ./fonts.nix
    ./fwupd.nix
    ./gc.nix
    ./graphics.nix
    #./hacking.nix
    ./i18n.nix
    ./info-fetchers.nix
    ./plasma.nix
    ./hyprland.nix
    ./i18n.nix
    ./kernel.nix
    ./networking.nix
    ./dns.nix
    ./firewall.nix
    ./nh.nix
    ./nix-settings.nix
    ./nix-tools.nix
    #./lsp.nix
    ./powermanagement.nix
    #./ollama.nix
    #./rust.nix
    #./virtualisation.nix
    ./xdg.nix
  ];
}
