{
  imports = [
    ./audio.nix
    #./bluetooth.nix
    ./bootloader.nix
    ./cachix.nix
    #./security.nix
    ./environment-variables.nix
    ./fonts.nix
    #./fwupd.nix
    #./gc.nix
    #./graphics.nix
    #./hacking.nix
    ./info-fetchers.nix
    ./kernel.nix
    ./networking.nix
    ./dns.nix
    ./firewall.nix
    ./nh.nix
    ./nix-settings.nix
    ./nix-tools.nix
    #./lsp.nix
    ./powermanagement.nix
    #./ollama.nix
    #./rust.nix
    #./virtualisation.nix
    ./xdg.nix
  ];
}
